#!/system/bin/sh
# Script to launch frandom at boot by Ryuinferno @ XDA

if [ -e /dev/frandom ]; then
  chmod 666 /dev/frandom
  chmod 666 /dev/erandom
  mv /dev/random /dev/random.ori
  mv /dev/urandom /dev/urandom.ori
  ln /dev/frandom /dev/random
  chmod 666 /dev/random
  ln /dev/erandom /dev/urandom
  chmod 666 /dev/urandom
fi